export const REQUEST_ARTISTS = 'REQUEST_ARTISTS';
export const REQUEST_ARTISTS_SUCCESS = 'REQUEST_ARTISTS_SUCCESS';
export const REQUEST_ARTISTS_FAIL = 'REQUEST_ARTISTS_FAIL';

export const REQUEST_ALBUMS = 'REQUEST_ALBUMS';
export const REQUEST_ALBUMS_SUCCESS = 'REQUEST_ALBUMS_SUCCESS';
export const REQUEST_ALBUMS_FAIL = 'REQUEST_ALBUMS_FAIL';

export const REQUEST_ARTIST = 'REQUEST_ARTIST';
export const REQUEST_ARTIST_SUCCESS = 'REQUEST_ARTIST_SUCCESS';
export const REQUEST_ARTIST_SUCCESS_FROM_CACHE = 'REQUEST_ARTIST_SUCCESS_FROM_CACHE';
export const REQUEST_ARTIST_FAIL = 'REQUEST_ARTIST_FAIL';

export const REQUEST_ALBUM = 'REQUEST_ALBUM';
export const REQUEST_ALBUM_SUCCESS = 'REQUEST_ALBUM_SUCCESS';
export const REQUEST_ALBUM_SUCCESS_FROM_CACHE = 'REQUEST_ALBUM_SUCCESS_FROM_CACHE';
export const REQUEST_ALBUM_FAIL = 'REQUEST_ALBUM_FAIL';